dist: trusty
language: java
jdk:
- oraclejdk8
install: skip
script:
- mvn -v
- mvn clean install -f master
- mvn clean install
- mvn clean install -f tycho-pom.xml
notifications:
  email:
    on_success: change
    on_failure: change
cache:
  directories:
  - "$HOME/.m2"
