#!/bin/bash
# ***************************************************************************
# Copyright 2015-2016 Data Access Technologies, Inc. (Model Driven Solutions)
#
# All rights reserved worldwide. This program and the accompanying materials
# are made available for under the terms of the GNU General Public License 
# (GPL) version 3 that accompanies this distribution and is available at 
# http://www.gnu.org/licenses/gpl-3.0.html.
# ***************************************************************************

if [ "$ALF_LIB" = "" ] 
then
  lib=""
else
  lib="-l $ALF_LIB"
fi

java -jar dist/fuml-eclipse.jar $lib $@
