#!/bin/bash
# ***************************************************************************
# Copyright 2011-2015 Data Access Technologies, Inc. (Model Driven Solutions)
#
# All rights reserved worldwide. This program and the accompanying materials
# are made available for under the terms of the GNU General Public License 
# (GPL) version 3 that accompanies this distribution and is available at 
# http://www.gnu.org/licenses/gpl-3.0.html.
# ***************************************************************************

if [[ "$ALF_LIB" == "" || "-v" = $@ ]]
then
  lib=""
else
  lib="-l $ALF_LIB"
fi

java -jar dist/alf.jar $lib $@
