/*******************************************************************************
 * Copyright (c) 2018 Data Access Technologies, Inc. (Model Driven Solutions)
 *  All rights reserved worldwide. This program and the accompanying materials
 *  are made available for use under the terms of the GNU General Public License 
 *  (GPL) version 3 that accompanies this distribution and is available at 
 *  http://www.gnu.org/licenses/gpl-3.0.html. For alternative licensing terms, 
 *  contact Model Driven Solutions.
 *******************************************************************************/
/* Generated By:JavaCC: Do not edit this line. ParseException.java Version 6.0 */
/* JavaCCOptions:KEEP_LINE_COL=null */
package org.modeldriven.alf.interactive.parser;

import org.modeldriven.alf.interactive.parser.Token;

/**
 * This exception is thrown when parse errors are encountered.
 * You can explicitly create objects of this exception type by
 * calling the method generateParseException in the generated
 * parser.
 *
 * You can modify this class to customize your error reporting
 * mechanisms so long as you retain the public fields.
 */
@SuppressWarnings("all")
public class ParseException extends org.modeldriven.alf.parser.ParseException {

	private static final long serialVersionUID = 1L;

	public ParseException(Token currentTokenVal,
			int[][] expectedTokenSequencesVal,
			String[] tokenImageVal
			) {
		super(initialise(currentTokenVal, expectedTokenSequencesVal, tokenImageVal));
		this.setCurrentToken(currentTokenVal);
		expectedTokenSequences = expectedTokenSequencesVal;
		tokenImage = tokenImageVal;
	}

	private void setCurrentToken(Token currentTokenVal) {
		if (currentTokenVal.next != null) {
			currentTokenVal = currentTokenVal.next;
		}
		beginLine = currentTokenVal.beginLine;
		beginColumn = currentTokenVal.beginColumn;
		endLine = currentTokenVal.endLine;
		endColumn = currentTokenVal.endColumn;
	}

	public ParseException() {
		super();
	}

	/** Constructor with message. */
	public ParseException(Token currentToken, String message) {
		super(message);
		this.setCurrentToken(currentToken);
	}

	private static String initialise(Token currentToken,
			int[][] expectedTokenSequences,
			String[] tokenImage) {
		String eol = System.getProperty("line.separator", "\n");
		int maxSize = 0;
		for (int i = 0; i < expectedTokenSequences.length; i++) {
			if (maxSize < expectedTokenSequences[i].length) {
				maxSize = expectedTokenSequences[i].length;
			}
		}
		Token tok = currentToken.next;
		String retval = "[" + tok.beginLine + ":" + tok.beginColumn + "] Encountered \"";
		for (int i = 0; i < maxSize; i++) {
			if (i != 0) retval += " ";
			if (tok.kind == 0) {
				retval += tokenImage[0];
				break;
			}
			retval += " " + tokenImage[tok.kind];
			retval += " \"";
			retval += add_escapes(tok.image);
			retval += " \"";
			tok = tok.next;
		}
		retval += "\".";
		return retval;
	}

}
/* JavaCC - OriginalChecksum=8dc207f12a5ba6f400268022dda9be93 (do not edit this line) */
