/* Generated By:JavaCC: Do not edit this line. AlfParserConstants.java */
package alf.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AlfParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int END_OF_LINE_COMMENT = 9;
  /** RegularExpression Id. */
  int IN_LINE_COMMENT = 14;
  /** RegularExpression Id. */
  int DOCUMENTATION_COMMENT = 17;
  /** RegularExpression Id. */
  int ABSTRACT = 19;
  /** RegularExpression Id. */
  int ACCEPT = 20;
  /** RegularExpression Id. */
  int ACTIVE = 21;
  /** RegularExpression Id. */
  int ACTIVITY = 22;
  /** RegularExpression Id. */
  int ALL_INSTANCES = 23;
  /** RegularExpression Id. */
  int ANY = 24;
  /** RegularExpression Id. */
  int AS = 25;
  /** RegularExpression Id. */
  int ASSOC = 26;
  /** RegularExpression Id. */
  int BREAK = 27;
  /** RegularExpression Id. */
  int CASE = 28;
  /** RegularExpression Id. */
  int CLASS = 29;
  /** RegularExpression Id. */
  int CLASSIFY = 30;
  /** RegularExpression Id. */
  int COMPOSE = 31;
  /** RegularExpression Id. */
  int CREATE = 32;
  /** RegularExpression Id. */
  int DATATYPE = 33;
  /** RegularExpression Id. */
  int DEFAULT_ = 34;
  /** RegularExpression Id. */
  int DESTROY = 35;
  /** RegularExpression Id. */
  int DO = 36;
  /** RegularExpression Id. */
  int ELSE = 37;
  /** RegularExpression Id. */
  int ENUM = 38;
  /** RegularExpression Id. */
  int FOR = 39;
  /** RegularExpression Id. */
  int FROM = 40;
  /** RegularExpression Id. */
  int HASTYPE = 41;
  /** RegularExpression Id. */
  int IF = 42;
  /** RegularExpression Id. */
  int IMPORT = 43;
  /** RegularExpression Id. */
  int IN = 44;
  /** RegularExpression Id. */
  int INOUT = 45;
  /** RegularExpression Id. */
  int INSTANCEOF = 46;
  /** RegularExpression Id. */
  int NAMESPACE = 47;
  /** RegularExpression Id. */
  int NEW = 48;
  /** RegularExpression Id. */
  int NONUNIQUE = 49;
  /** RegularExpression Id. */
  int NULL = 50;
  /** RegularExpression Id. */
  int OR = 51;
  /** RegularExpression Id. */
  int ORDERED = 52;
  /** RegularExpression Id. */
  int OUT = 53;
  /** RegularExpression Id. */
  int PACKAGE = 54;
  /** RegularExpression Id. */
  int PRIVATE = 55;
  /** RegularExpression Id. */
  int PROTECTED = 56;
  /** RegularExpression Id. */
  int PUBLIC = 57;
  /** RegularExpression Id. */
  int RECEIVE = 58;
  /** RegularExpression Id. */
  int REDEFINES = 59;
  /** RegularExpression Id. */
  int RETURN = 60;
  /** RegularExpression Id. */
  int SPECIALIZES = 61;
  /** RegularExpression Id. */
  int SUPER = 62;
  /** RegularExpression Id. */
  int SIGNAL = 63;
  /** RegularExpression Id. */
  int SWITCH = 64;
  /** RegularExpression Id. */
  int THIS = 65;
  /** RegularExpression Id. */
  int TO = 66;
  /** RegularExpression Id. */
  int WHILE = 67;
  /** RegularExpression Id. */
  int COLLECTION_NAME = 68;
  /** RegularExpression Id. */
  int IDENTIFIER = 69;
  /** RegularExpression Id. */
  int IDENTIFIER_LETTER_OR_DIGIT = 70;
  /** RegularExpression Id. */
  int IDENTIFIER_LETTER = 71;
  /** RegularExpression Id. */
  int DIGIT = 72;
  /** RegularExpression Id. */
  int UNRESTRICTED_NAME = 73;
  /** RegularExpression Id. */
  int NAME_CHARACTER = 74;
  /** RegularExpression Id. */
  int ESCAPE_CHARACTER = 75;
  /** RegularExpression Id. */
  int ESCAPED_CHARACTER = 76;
  /** RegularExpression Id. */
  int BOOLEAN_LITERAL = 77;
  /** RegularExpression Id. */
  int NATURAL_LITERAL = 78;
  /** RegularExpression Id. */
  int STRING_LITERAL = 79;
  /** RegularExpression Id. */
  int STRING_CHARACTER = 80;
  /** RegularExpression Id. */
  int LPAREN = 81;
  /** RegularExpression Id. */
  int RPAREN = 82;
  /** RegularExpression Id. */
  int LBRACE = 83;
  /** RegularExpression Id. */
  int RBRACE = 84;
  /** RegularExpression Id. */
  int LBRACKET = 85;
  /** RegularExpression Id. */
  int RBRACKET = 86;
  /** RegularExpression Id. */
  int SEMICOLON = 87;
  /** RegularExpression Id. */
  int COMMA = 88;
  /** RegularExpression Id. */
  int DOT = 89;
  /** RegularExpression Id. */
  int DOUBLE_DOT = 90;
  /** RegularExpression Id. */
  int COLON = 91;
  /** RegularExpression Id. */
  int DOUBLE_COLON = 92;
  /** RegularExpression Id. */
  int ARROW = 93;
  /** RegularExpression Id. */
  int THICK_ARROW = 94;
  /** RegularExpression Id. */
  int ASSIGN = 95;
  /** RegularExpression Id. */
  int GT = 96;
  /** RegularExpression Id. */
  int LT = 97;
  /** RegularExpression Id. */
  int BANG = 98;
  /** RegularExpression Id. */
  int HOOK = 99;
  /** RegularExpression Id. */
  int AT = 100;
  /** RegularExpression Id. */
  int DOLLAR = 101;
  /** RegularExpression Id. */
  int EQ = 102;
  /** RegularExpression Id. */
  int LE = 103;
  /** RegularExpression Id. */
  int GE = 104;
  /** RegularExpression Id. */
  int NE = 105;
  /** RegularExpression Id. */
  int SC_OR = 106;
  /** RegularExpression Id. */
  int SC_AND = 107;
  /** RegularExpression Id. */
  int INCR = 108;
  /** RegularExpression Id. */
  int DECR = 109;
  /** RegularExpression Id. */
  int PLUS = 110;
  /** RegularExpression Id. */
  int MINUS = 111;
  /** RegularExpression Id. */
  int STAR = 112;
  /** RegularExpression Id. */
  int SLASH = 113;
  /** RegularExpression Id. */
  int LOGICAL_AND = 114;
  /** RegularExpression Id. */
  int LOGICAL_OR = 115;
  /** RegularExpression Id. */
  int XOR = 116;
  /** RegularExpression Id. */
  int REM = 117;
  /** RegularExpression Id. */
  int LSHIFT = 118;
  /** RegularExpression Id. */
  int PLUSASSIGN = 119;
  /** RegularExpression Id. */
  int MINUSASSIGN = 120;
  /** RegularExpression Id. */
  int STARASSIGN = 121;
  /** RegularExpression Id. */
  int SLASHASSIGN = 122;
  /** RegularExpression Id. */
  int ANDASSIGN = 123;
  /** RegularExpression Id. */
  int ORASSIGN = 124;
  /** RegularExpression Id. */
  int XORASSIGN = 125;
  /** RegularExpression Id. */
  int REMASSIGN = 126;
  /** RegularExpression Id. */
  int HASH = 127;
  /** RegularExpression Id. */
  int DOUBLE_HASH = 128;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_END_OF_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_IN_LINE_COMMENT = 2;
  /** Lexical state. */
  int IN_IN_LINE_COMMENT_STAR = 3;
  /** Lexical state. */
  int IN_DOCUMENTATION_COMMENT = 4;
  /** Lexical state. */
  int IN_DOCUMENTATION_COMMENT_STAR = 5;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"//\"",
    "<token of kind 7>",
    "\"/*\"",
    "<END_OF_LINE_COMMENT>",
    "<token of kind 10>",
    "<token of kind 11>",
    "\"*\"",
    "<token of kind 13>",
    "\"/\"",
    "<token of kind 15>",
    "\"*\"",
    "\"/\"",
    "<token of kind 18>",
    "\"abstract\"",
    "\"accept\"",
    "\"active\"",
    "\"activity\"",
    "\"allInstances\"",
    "\"any\"",
    "\"as\"",
    "\"assoc\"",
    "\"break\"",
    "\"case\"",
    "\"class\"",
    "\"classify\"",
    "\"compose\"",
    "\"create\"",
    "\"datatype\"",
    "\"default\"",
    "\"destroy\"",
    "\"do\"",
    "\"else\"",
    "\"enum\"",
    "\"for\"",
    "\"from\"",
    "\"hastype\"",
    "\"if\"",
    "\"import\"",
    "\"in\"",
    "\"inout\"",
    "\"instanceof\"",
    "\"namespace\"",
    "\"new\"",
    "\"nonunique\"",
    "\"null\"",
    "\"or\"",
    "\"ordered\"",
    "\"out\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"receive\"",
    "\"redefines\"",
    "\"return\"",
    "\"specializes\"",
    "\"super\"",
    "\"signal\"",
    "\"switch\"",
    "\"this\"",
    "\"to\"",
    "\"while\"",
    "<COLLECTION_NAME>",
    "<IDENTIFIER>",
    "<IDENTIFIER_LETTER_OR_DIGIT>",
    "<IDENTIFIER_LETTER>",
    "<DIGIT>",
    "<UNRESTRICTED_NAME>",
    "<NAME_CHARACTER>",
    "<ESCAPE_CHARACTER>",
    "<ESCAPED_CHARACTER>",
    "<BOOLEAN_LITERAL>",
    "<NATURAL_LITERAL>",
    "<STRING_LITERAL>",
    "<STRING_CHARACTER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"..\"",
    "\":\"",
    "\"::\"",
    "\"->\"",
    "\"=>\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"?\"",
    "\"@\"",
    "\"$\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"#\"",
    "\"##\"",
  };

}
