/* Generated By:JavaCC: Do not edit this line. BaseParserImplConstants.java */
package org.modeldriven.alf.base.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
@SuppressWarnings("all")
public interface BaseParserImplConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SLASH_SLASH_AT = 6;
  /** RegularExpression Id. */
  int SLASH_STAR_AT = 7;
  /** RegularExpression Id. */
  int EOL = 8;
  /** RegularExpression Id. */
  int END_OF_LINE_COMMENT = 13;
  /** RegularExpression Id. */
  int IN_LINE_COMMENT = 19;
  /** RegularExpression Id. */
  int DOCUMENTATION_COMMENT = 22;
  /** RegularExpression Id. */
  int ABSTRACT = 25;
  /** RegularExpression Id. */
  int ACCEPT = 26;
  /** RegularExpression Id. */
  int ACTIVE = 27;
  /** RegularExpression Id. */
  int ACTIVITY = 28;
  /** RegularExpression Id. */
  int ALL_INSTANCES = 29;
  /** RegularExpression Id. */
  int ANY = 30;
  /** RegularExpression Id. */
  int AS = 31;
  /** RegularExpression Id. */
  int ASSOC = 32;
  /** RegularExpression Id. */
  int BREAK = 33;
  /** RegularExpression Id. */
  int CASE = 34;
  /** RegularExpression Id. */
  int CLASS = 35;
  /** RegularExpression Id. */
  int CLASSIFY = 36;
  /** RegularExpression Id. */
  int CLEAR_ASSOC = 37;
  /** RegularExpression Id. */
  int COMPOSE = 38;
  /** RegularExpression Id. */
  int CREATE_LINK = 39;
  /** RegularExpression Id. */
  int DATATYPE = 40;
  /** RegularExpression Id. */
  int DEFAULT_ = 41;
  /** RegularExpression Id. */
  int DESTROY_LINK = 42;
  /** RegularExpression Id. */
  int DO = 43;
  /** RegularExpression Id. */
  int ELSE = 44;
  /** RegularExpression Id. */
  int ENUM = 45;
  /** RegularExpression Id. */
  int FOR = 46;
  /** RegularExpression Id. */
  int FROM = 47;
  /** RegularExpression Id. */
  int HASTYPE = 48;
  /** RegularExpression Id. */
  int IF = 49;
  /** RegularExpression Id. */
  int IMPORT = 50;
  /** RegularExpression Id. */
  int IN = 51;
  /** RegularExpression Id. */
  int INOUT = 52;
  /** RegularExpression Id. */
  int INSTANCEOF = 53;
  /** RegularExpression Id. */
  int LET = 54;
  /** RegularExpression Id. */
  int NAMESPACE = 55;
  /** RegularExpression Id. */
  int NEW = 56;
  /** RegularExpression Id. */
  int NONUNIQUE = 57;
  /** RegularExpression Id. */
  int NULL = 58;
  /** RegularExpression Id. */
  int OR = 59;
  /** RegularExpression Id. */
  int ORDERED = 60;
  /** RegularExpression Id. */
  int OUT = 61;
  /** RegularExpression Id. */
  int PACKAGE = 62;
  /** RegularExpression Id. */
  int PRIVATE = 63;
  /** RegularExpression Id. */
  int PROTECTED = 64;
  /** RegularExpression Id. */
  int PUBLIC = 65;
  /** RegularExpression Id. */
  int RECEIVE = 66;
  /** RegularExpression Id. */
  int REDEFINES = 67;
  /** RegularExpression Id. */
  int REDUCE = 68;
  /** RegularExpression Id. */
  int RETURN = 69;
  /** RegularExpression Id. */
  int SEQUENCE = 70;
  /** RegularExpression Id. */
  int SPECIALIZES = 71;
  /** RegularExpression Id. */
  int SUPER = 72;
  /** RegularExpression Id. */
  int SIGNAL = 73;
  /** RegularExpression Id. */
  int SWITCH = 74;
  /** RegularExpression Id. */
  int THIS = 75;
  /** RegularExpression Id. */
  int TO = 76;
  /** RegularExpression Id. */
  int WHILE = 77;
  /** RegularExpression Id. */
  int BOOLEAN_LITERAL = 78;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 79;
  /** RegularExpression Id. */
  int STRING_LITERAL = 80;
  /** RegularExpression Id. */
  int STRING_CHARACTER = 81;
  /** RegularExpression Id. */
  int IDENTIFIER = 82;
  /** RegularExpression Id. */
  int IDENTIFIER_LETTER_OR_DIGIT = 83;
  /** RegularExpression Id. */
  int IDENTIFIER_LETTER = 84;
  /** RegularExpression Id. */
  int DIGIT = 85;
  /** RegularExpression Id. */
  int NONZERO_DIGIT = 86;
  /** RegularExpression Id. */
  int ESCAPE_CHARACTER = 87;
  /** RegularExpression Id. */
  int ESCAPED_CHARACTER = 88;
  /** RegularExpression Id. */
  int LPAREN = 89;
  /** RegularExpression Id. */
  int RPAREN = 90;
  /** RegularExpression Id. */
  int LBRACE = 91;
  /** RegularExpression Id. */
  int RBRACE = 92;
  /** RegularExpression Id. */
  int LBRACKET = 93;
  /** RegularExpression Id. */
  int RBRACKET = 94;
  /** RegularExpression Id. */
  int SEMICOLON = 95;
  /** RegularExpression Id. */
  int COMMA = 96;
  /** RegularExpression Id. */
  int DOT = 97;
  /** RegularExpression Id. */
  int DOUBLE_DOT = 98;
  /** RegularExpression Id. */
  int COLON = 99;
  /** RegularExpression Id. */
  int DOUBLE_COLON = 100;
  /** RegularExpression Id. */
  int ARROW = 101;
  /** RegularExpression Id. */
  int THICK_ARROW = 102;
  /** RegularExpression Id. */
  int ASSIGN = 103;
  /** RegularExpression Id. */
  int GT = 104;
  /** RegularExpression Id. */
  int LT = 105;
  /** RegularExpression Id. */
  int BANG = 106;
  /** RegularExpression Id. */
  int TILDE = 107;
  /** RegularExpression Id. */
  int HOOK = 108;
  /** RegularExpression Id. */
  int AT = 109;
  /** RegularExpression Id. */
  int EQ = 110;
  /** RegularExpression Id. */
  int LE = 111;
  /** RegularExpression Id. */
  int GE = 112;
  /** RegularExpression Id. */
  int NE = 113;
  /** RegularExpression Id. */
  int SC_OR = 114;
  /** RegularExpression Id. */
  int SC_AND = 115;
  /** RegularExpression Id. */
  int PLUS = 116;
  /** RegularExpression Id. */
  int MINUS = 117;
  /** RegularExpression Id. */
  int STAR = 118;
  /** RegularExpression Id. */
  int SLASH = 119;
  /** RegularExpression Id. */
  int REM = 120;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_STATEMENT_ANNOTATION = 1;
  /** Lexical state. */
  int IN_IN_LINE_ANNOTATION = 2;
  /** Lexical state. */
  int IN_END_OF_LINE_COMMENT = 3;
  /** Lexical state. */
  int IN_IN_LINE_COMMENT = 4;
  /** Lexical state. */
  int IN_IN_LINE_COMMENT_STAR = 5;
  /** Lexical state. */
  int IN_DOCUMENTATION_COMMENT = 6;
  /** Lexical state. */
  int IN_DOCUMENTATION_COMMENT_STAR = 7;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\f\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"//@\"",
    "\"/*@\"",
    "<EOL>",
    "<token of kind 9>",
    "<token of kind 10>",
    "\"//\"",
    "\"/*\"",
    "<END_OF_LINE_COMMENT>",
    "<token of kind 14>",
    "<token of kind 15>",
    "\"*\"",
    "\"*\"",
    "<token of kind 18>",
    "\"/\"",
    "<token of kind 20>",
    "\"*\"",
    "\"/\"",
    "\"*\"",
    "<token of kind 24>",
    "\"abstract\"",
    "\"accept\"",
    "\"active\"",
    "\"activity\"",
    "\"allInstances\"",
    "\"any\"",
    "\"as\"",
    "\"assoc\"",
    "\"break\"",
    "\"case\"",
    "\"class\"",
    "\"classify\"",
    "\"clearAssoc\"",
    "\"compose\"",
    "\"createLink\"",
    "\"datatype\"",
    "\"default\"",
    "\"destroyLink\"",
    "\"do\"",
    "\"else\"",
    "\"enum\"",
    "\"for\"",
    "\"from\"",
    "\"hastype\"",
    "\"if\"",
    "\"import\"",
    "\"in\"",
    "\"inout\"",
    "\"instanceof\"",
    "\"let\"",
    "\"namespace\"",
    "\"new\"",
    "\"nonunique\"",
    "\"null\"",
    "\"or\"",
    "\"ordered\"",
    "\"out\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"receive\"",
    "\"redefines\"",
    "\"reduce\"",
    "\"return\"",
    "\"sequence\"",
    "\"specializes\"",
    "\"super\"",
    "\"signal\"",
    "\"switch\"",
    "\"this\"",
    "\"to\"",
    "\"while\"",
    "<BOOLEAN_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<STRING_LITERAL>",
    "<STRING_CHARACTER>",
    "<IDENTIFIER>",
    "<IDENTIFIER_LETTER_OR_DIGIT>",
    "<IDENTIFIER_LETTER>",
    "<DIGIT>",
    "<NONZERO_DIGIT>",
    "<ESCAPE_CHARACTER>",
    "<ESCAPED_CHARACTER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"..\"",
    "\":\"",
    "\"::\"",
    "\"->\"",
    "\"=>\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\"@\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
  };

}
